### ISSUE TITLE
WeChat sandbox verify token failed

### ISSUE THREAD

**Issue by Iyata** [Eric-Guo/wechat-starter#40]
Hi, I'm Iyata from Nigeria.
I have been trying to verify wechat token from my sandbox account for days now. I my Laravel app returns the correct 'echostr' but sandbox config has been failing.
Help please.

**Comment by Eric-Guo** [comment]
Laravel is a PHP framework, this repo showing the Rails way to do the WeChat development, so I guess you probably open the correct issue in the wrong place?

**Comment by Iyata** [comment]
Oh yeah, my bad, thanks. Just been having challenges verifying the token on the sandbox. Any general comment on how the sandbox expects the 'echostr' to be sent back for verification?

**Comment by Eric-Guo** [comment]
I recommend you using the real account to do the testing (a free personal account is enough), using `sandbox` is wasting time, IMHO ....

**Comment by Iyata** [comment]
Thanks a lot, it has been resolved now.
